In [8]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [9]:
data = pd.read_csv('/Users/zhangweichen/OneDrive - UTS/Machine_Learning_Project/Project_without_framework/Perceptron/mushrooms_data.csv')

In [10]:
def map_value(dataset):
    encoder = LabelEncoder()
    for col in data.columns:
        data[col]=encoder.fit_transform(dataset[col])
    return dataset


In [11]:
data_new = map_value(data)
X=data_new.iloc[:,1:23]
y=data_new[['class']]

simple_x = data_new.iloc[:,1:].values
print(simple_x)
simple_y = data_new.iloc[:,0].values

simple_y[simple_y==0] = -1.0
print(simple_y.shape)

simple_x_train, simple_x_valid, simple_y_train, simple_y_valid = train_test_split(simple_x, simple_y)
print(simple_y)

[[5 2 4 ... 2 3 5]
 [5 2 9 ... 3 2 1]
 [0 2 8 ... 3 2 3]
 ...
 [2 2 4 ... 0 1 2]
 [3 3 4 ... 7 4 2]
 [5 2 4 ... 4 1 2]]
(8124,)
[ 1 -1 -1 ... -1  1 -1]


In [12]:
class MyPerceptron(object):
    def __init__(self,X):
        self.h = np.array(np.zeros(X.shape[1]+1))
        # self.h = np.array(np.zeros(X.shape[1]+1))

    def linear_function(self, X, h):
        """Compute the linear function"""
        x =  np.concatenate((X,np.ones((X.shape[0],1))),axis=1)
        s = x.dot(h.T)
        # s = (X * h[:-1]).sum(axis=1) + h[-1]
        return s

    def predict_with_(self, X, h):
        # return 0/1 according to the linear function

        return np.sign(self.linear_function(X, h)).astype(np.int)

    def predict(self, X):
        return self.predict_with_(X, self.h)

    def fit(self, X, y,n):
        """
        :param X: training samples
        :param y: the known answer for each sample

        """
        ii = 0
        while True:

            # predict using the current h
            predicted = self.predict_with_(X,self.h)

            # find errors
            error_indexes = np.nonzero(predicted != y)[0]

            if len(error_indexes) > 0:
                i = error_indexes[np.random.randint(len(error_indexes))]
                self.h[:-1] += X[i] * float(y[i])
                # To update the weights

                self.h[-1] += float(y[i])
                # To update the b-bias

                print(f"{ii} Train errors: {len(error_indexes)}")

                ii += 1

                if ii >= n:  # iteration size
                    break
            else:
                return self.h

In [19]:
my_model = MyPerceptron(simple_x_train) # initiate an object

my_model.fit(simple_x_train, simple_y_train,6000)
final_h = my_model.h
print(final_h)

0 Train errors: 6093
1 Train errors: 3178
2 Train errors: 2733
3 Train errors: 3179
4 Train errors: 1708
5 Train errors: 3178
6 Train errors: 1601
7 Train errors: 3171
8 Train errors: 2319
9 Train errors: 2893
10 Train errors: 1701
11 Train errors: 2042
12 Train errors: 1757
13 Train errors: 1878
14 Train errors: 1678
15 Train errors: 2603
16 Train errors: 1701
17 Train errors: 1876
18 Train errors: 1538
19 Train errors: 1722
20 Train errors: 3189
21 Train errors: 1536
22 Train errors: 2612
23 Train errors: 1530
24 Train errors: 2217
25 Train errors: 1247
26 Train errors: 1755
27 Train errors: 1267
28 Train errors: 2884
29 Train errors: 1164
30 Train errors: 1877
31 Train errors: 1159
32 Train errors: 2204
33 Train errors: 1756
34 Train errors: 3040
35 Train errors: 1162
36 Train errors: 3138
37 Train errors: 1126
38 Train errors: 2648
39 Train errors: 1074
40 Train errors: 3146
41 Train errors: 1024
42 Train errors: 2639
43 Train errors: 1200
44 Train errors: 1302
45 Train errors: 147

In [20]:
pred_valid = my_model.predict(simple_x_valid)
# pred_valid = my_model.predict()
print(pred_valid)
print(simple_y_valid)
valid_corr_num = (pred_valid == simple_y_valid).sum()
print("Valid accu", valid_corr_num / len(simple_y_valid))




[-1  1  1 ...  1  1 -1]
[-1  1  1 ... -1  1 -1]
Valid accu 0.896110290497292
